### PR TITLE
migrate into null safety

### PR DESCRIPTION
**Pull request by Nyamkhuub**
I will write IOS channel if I have time

### CODE REVIEW

**Comment by iamSahdeep** [comment]
Hi @Nyamkhuub Thanks for the PR.

I am happy to merge it but I am not maintaining this repo anymore. If you want I can add you as the maintainer and you can maintain it in your free time?

**Review by gafar-code — APPROVED** [review]

**Comment by Nyamkhuub** [comment]
@iamSahdeep okey add me as maintainer. I will take care of it when my free time.

**Comment by iamSahdeep** [comment]
Haha @Nyamkhuub Its been a while, sorry I was not available, give me a ping if you are still up for it..

**Comment by cheri-nonegolab** [comment]
I hope that this will proceed.

**Comment by Nyamkhuub** [comment]
> 

I already forked this project.

Link https://github.com/Nyamkhuub/FlutterVisualizers

**Pull request closed without merging**
